### ISSUE TITLE
App doesn't do anything for me on OS X

### ISSUE THREAD

**Issue by lancecarlson** [serge-hulne/Isomorphic-crystal#2]
When I try to run your app, it loads up the window and I think it loads Kemal.. but I think Kemal hangs because I just get a blank screen. How did you get your app working?

**Comment by serge-hulne** [comment]
It has to be compiled wi the following command:

crystal build -D preview_mt ./src/gui.cr -o MyApp

Otherwise, it can't use threads and Webview won't be able to load the app.
